// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID   pgtype.UUID `json:"user_id"`
	Username string      `json:"username"`
	GoogleID pgtype.Text `json:"google_id"`
	AppleID  pgtype.Text `json:"apple_id"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
	Avatar   pgtype.Text `json:"avatar"`
}
