// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, google_id, apple_id, name, email, avatar
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING user_id, username, google_id, apple_id, name, email, avatar
`

type CreateUserParams struct {
	Username string      `json:"username"`
	GoogleID pgtype.Text `json:"google_id"`
	AppleID  pgtype.Text `json:"apple_id"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
	Avatar   pgtype.Text `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.GoogleID,
		arg.AppleID,
		arg.Name,
		arg.Email,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GoogleID,
		&i.AppleID,
		&i.Name,
		&i.Email,
		&i.Avatar,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, google_id, apple_id, name, email, avatar FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GoogleID,
		&i.AppleID,
		&i.Name,
		&i.Email,
		&i.Avatar,
	)
	return i, err
}

const getUserByGoogleId = `-- name: GetUserByGoogleId :one
SELECT user_id, username, google_id, apple_id, name, email, avatar FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleId(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleId, googleID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.GoogleID,
		&i.AppleID,
		&i.Name,
		&i.Email,
		&i.Avatar,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, google_id, apple_id, name, email, avatar FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.GoogleID,
			&i.AppleID,
			&i.Name,
			&i.Email,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
  set name = $2,
  email = $3,
  avatar = $4
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Email  pgtype.Text `json:"email"`
	Avatar pgtype.Text `json:"avatar"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.Avatar,
	)
	return err
}
