# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :upload_app_to_testflight do
    sign_to_appconnect

    upload_to_testflight(
      app_platform: "ios",
      ipa: "../bazel-bin/ios/DeployApp.ipa",
    )
  end

  lane :update_build_number_for_testflight do
    sign_to_appconnect
    hardcodedSHA256 = "14cdbe80dc024fe4c2122b0350871ac142f11f5a525e1d2c4ff1c8498b6eb988"

    my_hash = {
      appId: ENV['APP_IDENTIFIER'],
      sha256: hardcodedSHA256
    }

    puts "Hash before encoded #{my_hash}"

    encoded_hash = Base64.strict_encode64(my_hash.to_json)

    puts "Hash encoded: #{encoded_hash}"

    build_output = `curl https://increment.build/#{encoded_hash}`

    # Remove leading and trailing whitespaces from the output
    build_number = build_output.strip

    # Check if the value is a number using a regular expression
    re = /^[0-9]+$/

    if !build_number.match?(re)
      UI.error("error: Not a number")
      exit 1
    end

    puts "Update Build Number to: #{build_number}"

    set_info_plist_value(
      path: "Resources/Info.plist",
      key: "CFBundleVersion",
      value: build_number
    )
  end

  lane :sign_to_appconnect do
    app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_filepath: ENV['API_KEY_PATH']
    )
  end
end
