# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :upload_app_to_testflight do
    sign_to_appconnect

    upload_to_testflight(
      app_platform: "ios",
      ipa: "../bazel-bin/ios/DeployApp.ipa",
    )
  end

  lane :update_build_number_for_testflight do
    sign_to_appconnect

    last_num = latest_testflight_build_number(
      app_identifier: ENV['APP_IDENTIFIER'],
    )

    set_info_plist_value(
      path: "Resources/Info.plist",
      key: "CFBundleVersion",
      value: (last_num + 1).to_s
    )
  end

  lane :sign_to_appconnect do
    app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_filepath: ENV['API_KEY_PATH']
    )
  end
end
