# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Description of what the lane does"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      aab: "../bazel-bin/android/app/android_app.aab",
    )
  end

  lane :change_version_code do
    result = google_play_track_version_codes(
      track: 'internal'
    )
    puts result
    # ENV["BUILD_NUMBER"] = result.to_s
    # sh("pwd")
    sh("../scripts/change_version_code.sh #{result[0] + 1}")
  end

end